name: e_commerce_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  awesome_dialog: ^3.1.0
  bloc: ^8.1.2
  dio: ^5.3.2
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  font_awesome_icon_class: ^0.0.6
  page_transition: ^2.1.0
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
